# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('alumni_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('letter', models.CharField(max_length=2)),
                ('add_time', models.DateTimeField()),
                ('added_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='invite_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_issued_by', models.BooleanField()),
                ('is_merged_to', models.BooleanField()),
                ('add_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='invites',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField()),
                ('alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumni')),
            ],
        ),
        migrations.AddField(
            model_name='invite_links',
            name='code_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links_from', to='app.invites'),
        ),
        migrations.AddField(
            model_name='invite_links',
            name='code_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links_to', to='app.invites'),
        ),
    ]
