# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('alumnus_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('letter', models.CharField(max_length=2)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Alumnus',
                'verbose_name_plural': 'Alumni',
            },
        ),
        migrations.CreateModel(
            name='invite_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_issued_by', models.BooleanField(default=False)),
                ('is_merged_to', models.BooleanField(default=False)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invite link',
                'verbose_name_plural': 'Invite links',
            },
        ),
        migrations.CreateModel(
            name='invites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumni')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
            },
        ),
        migrations.AddField(
            model_name='invite_links',
            name='code_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links_from', to='app.invites'),
        ),
        migrations.AddField(
            model_name='invite_links',
            name='code_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links_to', to='app.invites'),
        ),
    ]
