# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'verbose_name': 'Alumnus', 'verbose_name_plural': 'Alumni'},
        ),
        migrations.AlterModelOptions(
            name='invite_links',
            options={'verbose_name': 'Invite link', 'verbose_name_plural': 'Invite links'},
        ),
        migrations.AlterModelOptions(
            name='invites',
            options={'verbose_name': 'Invite', 'verbose_name_plural': 'Invites'},
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='alumni_id',
            new_name='alumnus_id',
        ),
    ]
