# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170112_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite_links',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invites',
            name='status',
            field=models.SmallIntegerField(choices=[(1, b'OK'), (2, b'DISABLED'), (3, b'BANNED')], default=1),
        ),
    ]
