# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160914_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='alumnus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invite_links',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invites',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
