# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170216_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('disabled', models.BooleanField(default=False)),
                ('valid_for', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='invite_links',
            name='is_temporary_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invites',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invites',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Application'),
        ),
    ]
