# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160914_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invites',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
