# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160914_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invites',
            old_name='alumni_id',
            new_name='alumni',
        ),
    ]
